@echo off
title Inteligencia Artificial Osito Games
color 0a
mode 1000
echo *******************************************************************************************************
echo ******************************* AVISO ** DE ** LICENCIA ***********************************************
echo *******************************************************************************************************
echo *
echo * Derechos Reservados A: ** Ernesto Ynfante ** esta licenciado bajo la GNU General Public License v3.0
echo *
echo * Los permisos de esta licencia de copyleft fuerte estan condicionados a poner a disposicion
eCHO *
echo * El codigo fuente completo de las obras y modificaciones con licencia,
echo *
echo * Que incluyen las obras mas grandes que utilizan una obra con licencia,
echo *
echo * Bajo la misma licencia.
echo *
echo * Deben preservarse los avisos de copyright y licencia.
echo *
echo * Los contribuyentes proporcionan una concesion expresa de derechos de patente.
echo *
echo *******************************************************************************************************
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyo/--......--:+sdmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms:.`  `..---::::-.` `-/ymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs.  .:oydmmNNNNNNNNmds/` `-sNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMm/` `odNNNNNNNNNNNNNNNNNNds. `-hMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMMMMMM
echo MMMMm+---/yNMMMMMMMMMMMMMMMMMMMMN:` .hNhNNNNNNNNNNNNNNNNNNNNm/  .hMMMMMMMMMMMMMMMMMMMMMMms:--:sNMMMM
echo MMMM-` `` `:hMMMMMMMMMMMMMMMMMMM+` `dNNhNNNNNNNNNNNNNNNNNNNNNN/  .mMMMMMMMMMMMMMMMMMMMNs-` .. `+MMMM
echo MMMM.` /d/` `+NMMMMMMMMMMMMMMMMN`  oNNymNNNNNNNNNNNNNNNNNNNNNNN. `+MMMMMMMMMMMMMMMMMMh-` `+my `-MMMM
echo MMMMo` `hNy- `-yNMMMMMMMMMMMMMMh`  hNdhNNmmmmmNNNNNNNmmmmNNNmNMo  .MMMMMMMMMMMMMMMMm/` `/hNN- `oMMMM
echo MMMMN-` -mNNs. `:yNMMMMMMMMMMMMy`  dNhNN/-...-sNNNNh:...-oNM+mNo  `MMMMMMMMMMMMMMm+.` -hNNN+ `-NMMMM
echo MMMMMm-` :mNNmo. `-sNMMMMMMMMMMm`  yNoNN      -NNmNo`     hModm- `:MMMMMMMMMMMMm+.` .sNNmm/ `-mMMMMM
echo MMMMMMd-` :dNNNms. `.+dMMMMMMMMM/` -s+NNs```.omN:.hNdo-``:mNhs-  `dMMMMMMMMMNh+.` .smNdyh- `:mMMMMMM
echo MMMMMMMm:` `sNNNNNs-  `:yNMMMMMMh`  oNNNNNdmNNM+  `hNNNNNNNNNNy  `mMMMMMMMms:`` -yNNNyhs` `+NMMMMMMM
echo MMMMMMMMMs.` -hNNNNNh/` `.+hNMMMN-` .sdyoohNNNN/s+`oNNNNNsosyo. `:MMMMMNy/.` `+hNNmhhh- `-hMMMMMMMMM
echo MMMMMMMMMMm+`  :hNNNNNms-  `.odMMNo.` `hh:`dNNNNNNmNNNNN/oNo   `+NMMNy+.`  :yNNNdsyh:  .oNMMMMMMMMMM
echo MMMMMMMMMMMMd/`` :hNNNNNNmo-  `.+hNm`  sNN`.myNmNmmmhNh`/NN. `+NMNy/.`  -smNNNmyys-  `+NMMMMMMMMMMMM
echo MMMMMMMMMMMMMMd/`` .omNNNNNNdo-  ``/.` :NM+`+:h:s++y`o/ hMy  `hs/``  :smNNNNNNd+`  `+mMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMm+.` `/ymNNNhhdms:`  ` .mNN+oNsdm+doyNoyNN- ```` ./ymdhhmNNms-   .oNMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMNy:`` `+ymNNdyydNh+-  `:smmmNmNmNmNNNms.   `:ohmhyydNNms:`  `/hMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMmo:````/ymNmdsyhmmy+-`.+hyyhhhhhy/` ./ohmdhyydNNmy/`  `:yNMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMmy+:.```  `:shmmmdhddmmds+-`   `.:+sdmmdhyhmmmho:`  ```-+smMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMN+`   ```      `.+shmmmdddddmmhs+shhhdddmmmmhs/.`      `.`  .+NMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMo` `sdmmmh+.       `./shdmmmhhdddmmmhdddhs/.`       :sdmmmh- `+MMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMNho/---.` .mNNNdNNm+  .-:+shdmdy+oyddmmmdhhhdddddhyo/:-. -hNNmmNNN/ `.:::+shNMMMMMMMMMMMM
echo MMMMMMMMMMy-`  `.  `.`-ss:-+mNNy+yyyyyyyydmmmdhy+/oyhmmmmmhhhddyysyomNNs:-+s/`..  ..` `-yMMMMMMMMMMM
echo MMMMMMMMMh`  /hdmd/hmdsmmsmmymNNmh+ydmmmdys/-.```````.-/oyhdmmmds:dNNNyymydmdymmsydmdo` `sMMMMMMMMMM
echo MMMMMMMMM+` .mNNNmy+mNmNNNNNNsmNN+oo+:-.````.-:/oyy+/-.` ``..-/+s-hNNyhNNNNNNNNs+mNNNN/ `+MMMMMMMMMM
echo MMMMMMMMMy`  odNms++.://////:`yNNy  .` ``:shmmNMMMMMMNmdho``` `` -mNm`-/////::-:osdNmy` `yMMMMMMMMMM
echo MMMMMMMMMMs.` .:::.``.......` .dNNyydd: `/MMMMMMMMMMMMMMMs. `sddshNN/  `......``.:::.  `+MMMMMMMMMMM
echo MMMMMMMMMMMms/-...-/sdmmmmmd-` .sdmmmd: `:MMMMMMMMMMMMMMMy`  odmmdh/ `-hmmmmmmy:.```.-+hMMMMMMMMMMMM
echo MMMMMMMMMMMMMMNmmmNMMMMMMMMMm+.` .---. `-dMMMMMMMMMMMMMMMMo.` .--.` ./mMMMMMMMMMmdddmNMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMds/-----/yNMMMMMMMMMMMMMMMMMMms:----/sdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
pause >NUL
goto oso

:oso
cls
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMNNMMMMMMMNNNMMMMNMMMMMMMNMMMMMMMNNNMMMMMMMMMMMMMMMNNNMMMMMMMMMMMNNMMMMMMMMMNNNMMMMMMNNNMMMMMMMMMMMNMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMh/.   `.omMMMy:`  `.`/Nh.    oh. ``````` :NMmo-`   `/hMMMMMMMMNs-`   ...hMMMMMM-  -dMMMMMh`   `hMMd.   -M/`````--` :MNo-   `.`oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMM+   smo    yM+    hNh:`hMs   -M. :d.   ss` yy`  /my`   /MMMMMMh`  .dMNo` :MMMMMm     yMMMMMo     hd`   `NMN`   hMydo/M-   .mNy.`mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMh    NMM+    ms     `./yMMy   :MMNMM-   hMNNN`   yMMh    sMMMMM`   yMMMNmhNMMMMN- o`   yMMMMs     ``    .MMM.   /+ -MMM/     `-+dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMh    +MMd    mdd+-      oMy   :MMMMM-   hMMMM`   -NMM.   sMMMMM.   :Md-`   :NMM: -s/    yMMMs  y    /   .MMM.   os`/MmNhh/.      yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMM+    od+  `sM.`smNy    oMo   -MMMMm    yMMMMh`   :dy`  /MMMMMMd.   :hd-  oMMN/ :+++/   `hMM/  Ms  +h   `NMN`   hMNNs + .yNNo    hMMds/+sNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMd+.`  `-oNMMd:.`   ./yMh`   `oMMd.    .dMMMMmo-`  `-+dMMMMMMMMNs/.   ./dMMy`  .dMN-    `+h`  /No+m.    /M/````.--.`.Ny:``   .+dMMMho//+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs/-.-:+ymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMds/:..:+hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo`         -hMMmhoo+ooydNMMMMMMmhsooooshNMMs.         `hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/    +hhyo.   :`          .:++-`          --   :shhy:    yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo    hMMNymd`                                  -NdyMMM/    hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.   `MMNo.                                        -yMMd    /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd-   -++.                                          :+/`  `+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms+-       .:`                            ./        /oyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs`       `mMdo:`                    ./smMy        .dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/          `odNNmy:    .--::--`   `/hNNmh/           yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs                     :mMMMMMMMMh.                     mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.                    sMMMMMMMMMMMN/                    +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.                  `dMMMMMMNMMMMMMMo                   +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy                  hMMy/:/o+++::+dMM+                 `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy.               oMMM/ :/.  -/-`sMMM-               :mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs`             NMMMMMMMN-+MMMMMMMMy             -hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs`          -MMMMMMMMM/dMMMMMMMMd           -yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy-         mMNhyyhyy:/yyhyyhMMs         /dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms-      .myhmMNhysyydNNdydy`     `:yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms-     :ydNNNNNNNNMNds-    `/yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy/`     ..-::-.`     .+hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdo:`oo:   `/s/`/smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
pause >NUL
goto gordo


:Gordo
cls
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMmhs+/:-......-:/oydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd/NMMMMMMMMdo/-`                    .:ohmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm/MMMMMMMMy-NMMMMMms:`                              ./ymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN-/MMMMMMN/-mMMMmo-                                      .+hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/ dMMMMMh.-NMMh:`                                           `/hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo /MMMMm/ :NMy- `-/syhddhhyo/.                                  `+dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs .NMMMs` /Nd:-+dNMMMMmhyymMMMNh-                                   /dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs `hMMh-  +NMymMMMdy+:-+ymNMMMMMMNs`                                  `/dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo  sMd/  `sMMMNho:`./shhys+/:://+osms                           -/-      `/mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/ `ym+`  .dMms:`   .-.``    -+ydNNMMMy                   ./:`     `+h+`     `oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh. `ss`   /ds-`                 ```.-/s.                    `/yh/`    .smo.     -hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm/   -.    -:`                                  .::.            `:dmo.    -dNo`    `+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMmo`                                               yNNNd+`   `+/     `/mNo`   `+Nm/     .hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMmo`                           /`    `+`             :mMMMMNs-   +d/`    .yMN+`   .hNh-    `oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMNh/`                      /:   `ss`.--+m+     --        `-oNMMMNy-  :mm+`    +NMm/   `oNNs.    -dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMd+.   `:-                  :NsoyhmMNNNNNMMms//sh+`           .oNMMMNs. .dMm+`   -hMNh-   -dMm+    `oNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMh-`    /dm.             .:+shNMMMMMNdysymMMMMMMMN:               .hMMMMNs.`sMMm+`  `oNMNy.  `oNMh-    :dMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMM.    `/dy.            `//::/oshohNs++/:``:smMMMMMNh/-:/:          `oNMMMMmo-:dMMm/`  -dMMmo.  -yMNo`   `sNMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMy     ```                .:oo//smNdhhdNNm.  -MMMMhMMMNs:`        :.  /NMMMMMNhosNMMd/` `oNMMmo`  /dMm/    :dMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMmo`      `--.              ``.+hNh/----`.os`  .MMNy.NMMm           :mo` /MMMMMMMMNMMMMMm+` -hMMMm+. `oNMh:   `+mMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMmy:`    :+ydmy/`             ./ymMmosdmdhd/       --.`oMMMN.          `NMd. oMMMMMMMMMMMMMMMms-`/dMMMms. .yNNy-   .sMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMNmho-`      :NMNy-` .:+sy.      `/yddmMNNNy--.``    -/oosshMMMMMs-          mMMm- hMMMMMMMMMMMMMMMMNd+-:hMMMNy:`-yNNo.   :dMMMMMMMMMMMMMMMMMMM
echo MMMMMNo-.`     ....-:++- .+hmNMNs`     `-:+shmMMm+odmd:   .yNMMMNNNNMMM+``          +MMMm.:MMMMMMMMMMMMMMMMMMMNh+/smMMNh/.-yNms.  `/mMMMMMMMMMMMMMMMMM
echo MMMMMMNh/.   ``./ydNd: -yymmmhs-  .:oydmNMMMMMMMNNmdo-  `/mmhs/-....:++              mMMMy mMMMMMMMMMMMMMMMMMMMMMNdyhNMMMms::hNmo-  `+mMMMMMMMMMMMMMMM
echo MMMMMMMMMmy:..ohhhdy.`sNMs-.``  .hmMMMMMMMMMNmhs/-.`  .+ys/.                         oMMMM:yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNds+hNNy:` `+dMMMMMMMMMMMMM
echo MMMMMMMMMMMMmy+/yNs`-dho+:`    /mMMMMMMMMMd+-`     `./+-.                        -   +MMMMdsMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmyhMNmo- `:hNMMMMMMMMMM
echo MMMMMMMMMMMMMMMNd/ `mMmy+:.`   oNMMMMMMNh:`        ``                           :N-  oMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMNdo-`-smMMMMMMMM
echo MMMMMMMMMMMMMMMm: `hMMMMMMmdyo::/sdMNmy:.....```                               +NM/  yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdo:./hNMMMMM
echo MMMMMMMMMMMMMNs.  sMMMMMMMMMMMMNNmmMNmdmmmmmmddhyo/:.                         -NMM: .NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmy+/oydNM
echo MMMMMMMMMMMms.   :MMMMMMMMMMMMMMNmdhyso++//:--...``                          .dMMM. sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmddmM
echo MMMMMMMMNy/.    .mMMMMMMMMMMmho/-.`                                  `./:   `hMMMd /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMNh+::+yo  `hMMMMMMMNho:`                                   `.-/ydNm.  `hMMMM+:NMMMMMMMNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMms/+ymNMh. `yMMMMMMms-                                 `.-:+ydmNMMMm-  -dMMMMNoNNmhyo/:------:+oydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MNo/ymMMMd+` :dMMMMMm+.                      `..      -+yhdmNMMMMMMMMd. .sNMMMMMNy/-`               `-+hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo d+yNMMmy/``:yNMMMMNs.               `/s-  `/hdmy   `:hNMMMMMMMMMMMMNs``/mMMMMMd+-                      `/mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo omMMd+. ./hNMMMMMm:           `:`  :dN+  :dMMMh`  :hMMMMMMMMMMMMMMm/`/dMMMMNy:`       `.-+syyys+-`       .hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMd/``:smMMMMMMMd-           :dm` +NMo `sNMMMm` `sNMMMMMMMMMMMMMNs:odMMMMmo.       `:shmMMMMMMMMMds.      `dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo Ns`.+dMMMMMMMMMd.           oNMy oMMh .dMMMMN: -dMMMMMMMMMMMMMNh+yNMMMNd/`       -sdMMMMMMMMMMMMMMMm/      -NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo :.omMMMMMMMMMMm.           /MMMs-MMN-.dMMMMMo -mMMMMMMMMMMMMMMhdMMMMNh:`      `:hNMMMMMMMMMMMMMMMMMMN+      dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo /mMMMMMMMMMMMM/            dMMMsyMMy.dMMMMMm`-mMMMMMMMMMMMMMMMMMMMms-       `+hMMMMMMMMMMMMMMMMMMMMMMd      yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMd             NMMMNMMM/yMMMMMM+`dMMMMMMMMMMMMMMMMMNd+.       .omMMMMMMMMMMMMMMMMMMMMMMMMs      dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMs  `s`        hMMMMMMMdMMMMMMN.yMMMMMMMMMMMMMMMMms:`       .smMMMMMMMMMMMMMMMMMMMMMMMMMN-     .NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMM:  yM/        .dMMMMMMMMMMMMMm-MMMMMMMMMMMMMNmh/`        .sNMMMMMMMMMMMMMMMMMMMMMMMMMMMo      oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMM- /MMd`        .sNMMMMMMMMMMMNmMMMMMMMMMNmds:.        `-yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMs`     /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMM- hMMM+          -odNNMMMMMMMMMMMMMNmdy+-`          `/hNMMNNMMMMMMMMMMMMMMMMMMMMMMMMm+     `sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMM+`NMMMm`            .-/+osyyyysoo//-.             -odNNdhyydMMMMMMMMMMMMMMMMMMMMMNmo.    `/dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMh`NMMMMs                                         ./////sdMMMNhsdMMMMMMMMMMMMMMMmy:`    `/hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMN+MMMMMN:    `                                 ``-+ydNMMNds//yNMMMMMMMMMMNNmho/`    `-smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMm.  `ds:``                     ``.-:+oydNMMMMNd+-`:hMMMMMMNNmhso/:.`    `.:ohNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMd.  hMMNho-`              `./sdNNMMMMMMMMMmo.  .yNNNmhs+/-.    ```.:+symMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMm- `mMMMMMNyo:.`       `+hNNMMMMMMMMMMNd/`   .so/-.   ``.:/oshdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMN/ :NMMMMMMMMMdyo+-.`````.-/oyhdNMMMm:         ``-+shdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMy.:dMMMMMMMMMMMMMMNmddhhyyhhhhdMm+`      `-+sdmNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMNs-dMMMMMMMMMMMMMMMMMMMMMMMMMNs`       `...```````..::+oshdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNomMMMMMMMMMMMMMMMMMMMMMMMm:             ``:/oyyddmmmmmmdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh.          `.+ydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+         ./yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh.       .+dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/      .+hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs.    .odMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs-  `:smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd+` .+hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms:-+ymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMysdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
pause >NUL
goto Matrix

:Matrix
echo %random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%
echo %random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%
goto Matrix